- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow ssh
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow Pod Routing
  community.general.ufw:
    rule: allow
    from: 10.244.0.0/24
    to: any

- name: Allow Service Routing
  community.general.ufw:
    rule: allow
    from: 10.96.0.0/12
    to: any

- name: Allow etcd
  community.general.ufw:
    rule: allow
    port: '2380'
    proto: tcp

- name: Allow kube-apiserver
  community.general.ufw:
    rule: allow
    port: '6443'
    proto: tcp
  
- name: Allow kube-router
  community.general.ufw:
    rule: allow
    port: '179'
    proto: tcp

- name: Allow kubelet
  community.general.ufw:
    rule: allow
    port: '10250'
    proto: tcp

- name: Allow k0s-api
  community.general.ufw:
    rule: allow
    port: '9443'
    proto: tcp

- name: Allow konnectivity
  community.general.ufw:
    rule: allow
    port: '8132'
    proto: tcp

- name: Allow NodePort NGINX Ingress
  community.general.ufw:
    rule: allow
    port: '30080'
    proto: tcp
    state: enabled